// Code generated by go2go; DO NOT EDIT.


//line /home/john/dev/jbert/aoc2020/src/aoc/bitmap/bitmap_test.go2:1
package bitmap

//line /home/john/dev/jbert/aoc2020/src/aoc/bitmap/bitmap_test.go2:1
import (
//line /home/john/dev/jbert/aoc2020/src/aoc/bitmap/bitmap_test.go2:1
 "fmt"
//line /home/john/dev/jbert/aoc2020/src/aoc/bitmap/bitmap_test.go2:1
 "testing"
//line /home/john/dev/jbert/aoc2020/src/aoc/bitmap/bitmap_test.go2:1
)

//line /home/john/dev/jbert/aoc2020/src/aoc/bitmap/bitmap_test.go2:7
func TestBitmap(t *testing.T) {
	b := New(10)

	err := b.Set(10)
	if err == nil {
		t.Fatalf("Shouldn't be able to set at size")
	}
}

//line /home/john/dev/jbert/aoc2020/src/aoc/bitmap/bitmap_test.go2:14
var _ = fmt.Errorf
//line /home/john/dev/jbert/aoc2020/src/aoc/bitmap/bitmap_test.go2:14
var _ = testing.AllocsPerRun
